spring.application.name=TaskFlow

spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://localhost:3306/TaskFlowDB
spring.datasource.username=taskUser
spring.datasource.password=htreniregw
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql: true

# Security Configuration
security.rsa.public.key=classpath:app.pub
security.rsa.private.key=classpath:app.key